tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
    before: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
      python ./bin/ecr/login
  - name: postgres
    init: |
    before: |
      curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc|sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
      echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
      sudo apt update
      sudo apt install -y postgresql-client-13 libpq-dev
    command: |
      export GITPOD_IP=$(curl ifconfig.me)
      source  "$THEIA_WORKSPACE_ROOT/bin/rds/update-sg-rule"
  - name: "Install Front-End dependencies"
    before: |
      ruby "$THEIA_WORKSPACE_ROOT/bin/frontend/generate-env"
      cd ./frontend-react-js
      npm i
      gp sync-done "Install Front-End dependencies"
  - name: "docker-compose up"
    before: |
      gp sync-await "Install Front-End dependencies"
      docker compose -f "./docker-compose.yml" up -d --build
      gp sync-done "docker-compose up"
  - name: db & ddb setup
    init: |
      gp sync-await "docker-compose up"
      echo "Waiting for 10 seconds..."
      sleep 10
      echo "Done waiting."
      ./bin/db/setup
      ./bin/ddb/schema-load
      ./bin/ddb/seed
  - name: flask
    command: |
      ruby  "$THEIA_WORKSPACE_ROOT/bin/backend/generate-env"
      cd backend-flask
      pip install -r requirements.txt
  - name: fargate
    before: |
      cd /workspace
      curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
      sudo dpkg -i session-manager-plugin.deb
      cd $THEIA_WORKSPACE_ROOT
      cd backend-flask
  - name: cdk
    before: |
      npm install aws-cdk -g
      cd thumbing-serverless-cdk
      cp .env.example .env
      npm i
vscode:
  extensions:
    - 42Crunch.vscode-openapi
    - cweijan.vscode-postgresql-client2

ports:
  - name: frontend
    port: 3000
    onOpen: open-browser
    visibility: public
  - name: backend
    port: 4567
    visibility: public
  - name: xray-daemon
    port: 2000
    visibility: public
